### ISSUE TITLE
Use embeddable version of Kotlin compiler

### ISSUE THREAD

**Issue by Darkyenus** [pfn/kotlin-plugin#1]
There are two [Kotlin compiler distributions](http://search.maven.org/#search%7Cga%7C1%7Ckotlin-compiler), both contain (not depend on!) a few libraries, most notably Google Guava. Due to this, when `kotlin-plugin` is added as a dependency alongside with other plugins which depend on different version of Guava, things break with hard-to-trace errors. Kotlin is aware of this and publishes `embeddable` version which relocates all baked dependencies into different package, thus fixing this problem.

Workaround ~~is~~ **EDIT:** _would be_ to add this plugin with:

```
addSbtPlugin("com.hanhuy.sbt" % "kotlin-plugin" % "0.9.2" exclude("org.jetbrains.kotlin", "kotlin-compiler"))

libraryDependencies += "org.jetbrains.kotlin" % "kotlin-compiler-embeddable" % "1.0.0-beta-2423"
```

which is not very clean. _But the plugin uses some of the libraries which are relocated and breaks._

Adding `-embeddable` after `kotlinLib("compiler` in `build.sbt` _and changing imports_ should be enough.

**Comment by pfn** [comment]
Thanks for investigating this and coming up with the workaround and solution. 

Can you submit the solution as a pr? It's trivial, but I don't have much time to get to this right now

**Comment by CluEleSsUK** [comment]
There seems to be a regression here.  I am having the same issue using 1.3.31 and maven.  Adding exclusions for guava to both the kotlin-compiler dependency and the kotlin-compiler plugin seem to have no effect
