### ISSUE TITLE
using kotlin code in java

### ISSUE THREAD

**Issue by strattonbrazil** [pfn/kotlin-plugin#10]
I'm trying to integrate kotlin into my java code.  I did this previously with scala, where I made scala file and used in java.  Now after adding the kotlin plugin, when I make a kotlin class in the same package, the java file can't find it.  

Do I need to do anything besides adding the plugin and executing "sbt run"?

**Comment by pfn** [comment]
Hmm, I didn't see this issue come in while I was on vacation at the time

classes in the same package should be visible, the test case [kotlin/mixed](src/sbt-test/kotlin/mixed) demonstrates this, `demo.KotlinB` extends `demo.JavaA` and `demo.JavaB` extends `demo.KotlinA`

I assume no further remarks/followups means this has been resolved on your end?
