### ISSUE TITLE
Problem with Kotlin 1.1.2

### ISSUE THREAD

**Issue by jrgonzalezg** [pfn/kotlin-plugin#12]
If i try to use 1.1.2 as KotlinVersion it fails with the following errors:
```
[error] Unable to find Args class
[error] (root/compile:kotlinCompile) Unable to find Args class
```
it works well if i use 1.1.1 or the default version. Any idea how to fix it?

**Comment by pfn** [comment]
update to 1.0.7

**Comment by jrgonzalezg** [comment]
Great!. Thanks for the fast fix :+1:
