### ISSUE TITLE
Problem compiling Kotlin 1.1.3-2

### ISSUE THREAD

**Issue by joshtrotter** [pfn/kotlin-plugin#14]
Similar to previously raised issue #12 which was resolved in plugin version 1.0.7, the plugin fails to compile when using Kotlin version 1.1.3-2

[error] (***/compile:kotlinCompile) Unable to find Args class
[error] (***/compile:kotlinCompile) Compilation failed. See log for more details

**Comment by pfn** [comment]
fixed by #16
