### ISSUE TITLE
Problem with Kotlin 1.1.4-2

### ISSUE THREAD

**Issue by YounesRahimi** [pfn/kotlin-plugin#18]
I use Kotlin 1.1.4-2 with kotlin-plugin v1.0.7, but following error occurs on compiling:

    [error] Unable to find Args class
    [error] (compile:kotlinCompile) Unable to find Args class

My build.sbt configuration is this:

    name := "scala-reflection"
    organization := "EPFL"
    version := "0.1"
    scalaVersion := "2.11.7"
    /*resolvers += ScalaToolsSnapshots*/
    libraryDependencies <+= scalaVersion("org.scala-lang" % "scala-reflect" % _)
    //we are using virtual pattern matcher as it's seems to be the only way to have
    //patterns workin with abstract types
    scalacOptions ++= Seq("-deprecation", "-unchecked", "-Xexperimental", "-feature")

    kotlinVersion := "1.1.4-2"
    kotlincOptions += "-verbose"
    kotlinLib("stdlib")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jre8
    kotlinLib("stdlib-jre8")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
    kotlinLib("reflect")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-noarg
    kotlinLib("noarg")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test
    kotlinLib("test")
    // https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test-junit
    kotlinLib("test-junit")
    val listClasses = taskKey[Unit]("listClasses")
    listClasses := {
      val classes = (classDirectory in Compile).value.***.get
      streams.value.log.info("classes: " + classes)
    }

**Comment by pfn** [comment]
this should be fixed by #16 but I have not yet released a new version including this yet

**Comment by pfn** [comment]
fixed by 27c23c6
