### ISSUE TITLE
kotlinCompileOrder not found

### ISSUE THREAD

**Issue by abond** [pfn/kotlin-plugin#3]
Hello!
When I try to set 
kotlinCompileOrder := KotlinCompileOrder.KotlinAfter
I get not found error. Am I doing something wrong, or this option not available now?
Thanks!

**Comment by pfn** [comment]
kotlinCompileOrder is an anachronism if it's mentioned in the README.
kotlin detects java sources ok and will handle mixed-mode compilation.

**Comment by pfn** [comment]
if you could submit a PR to remove the reference to kotlinCompileOrder, I
would appreciate it, thanks.

**Comment by pfn** [comment]
fixed by 1e6e0d1fafc9bc58b583c92747fd2aa204582d47
