### ISSUE TITLE
Annotation Processing

### ISSUE THREAD

**Issue by ScottPierce** [pfn/kotlin-plugin#6]
Kotlin processes annotations slightly different from Java. The Kotlin gradle plugin requires some special syntax for annotation processors (`kapt` instead of `compile`). Would annotation processors for Kotlin with this plugin? If so, does anything special need to be done?

**Comment by pfn** [comment]
If it works like java, then the annotation processor only needs to be on classpath. If it's a compile-time only dependency, you can use `libraryDependencies += group % artifactid % version % "compile-internal"`

**Comment by pfn** [comment]
I assume "compile-internal" is sufficient
